name: smarthome
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  fluttericon: ^2.0.0
  google_fonts: ^5.1.0
  ui_common:
    git: https://github.com/brocodev/ui_common.git
  image_picker: ^0.8.4+4
  get: ^4.6.6
  dotted_border: ^2.1.0
  http: ^1.0.0
  webview_flutter: ^4.4.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  firebase_messaging: ^14.7.5
  appwrite: ^11.0.1
  get_storage: ^2.1.1
  rxdart: ^0.27.7
  firebase_auth_mocks: ^0.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  mockito: ^5.4.3
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
